# Generated by Django 5.2.1 on 2025-05-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userasset',
            name='name',
        ),
        migrations.RemoveField(
            model_name='userasset',
            name='price',
        ),
        migrations.AlterField(
            model_name='userasset',
            name='holdings',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name='userasset',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
