# Generated by Django 5.2.2 on 2025-06-14 09:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_userasset_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='userasset',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
